version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ${DOCKER_FILE:-Dockerfile}
    env_file:
      - .env
    command: yarn start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
